### PR TITLE
Ported loam_continuous to indigo.

### PR DESCRIPTION
**Pull request by gtinchev**
Translated LaserScan to PointCloud2, as loam_continuous expects that as input.

### CODE REVIEW

**Comment by mauricefallon** [comment]
just gave you write access. For all small repos like this we make branches in the ipab-slmc repo directly.

how has this been tested?

**Comment by gtinchev** [comment]
I have downloaded and "catkin_make" on indigo (previously on Fuerte). Compiled okay.
I also tried the translator, seems to translate the laser scan okay (video below).
The only issue remaining is the rate of scan, I believe.
This is the result I get playing the husky log with it:
[https://www.dropbox.com/s/p4p1a2hk2mv968y/loam_multisense_odometry_off.ogv?dl=0](https://www.dropbox.com/s/p4p1a2hk2mv968y/loam_multisense_odometry_off.ogv?dl=0)

---

TODO:
- [x] Change the parameters of the spinning lidar to fix the odometry.
- [x] Publish an outline of the algorithm in the wiki.

**Comment by mauricefallon** [comment]
Ok, great to see you've been able to hook the systems together. The video is a bit difficult to understand but I assume it shows that the algorithm isn't working just yet.

Before doing an outdoor experiment, you should explore changing the speed of rotation. You should also be able to work out the spin rate of the device in the LOAM videos (or email the Author).
At the least the algorithm should estimate no motion when the robot is stationary in G.17 without diverging widely like this.

BTW, the camera images in the LCM log were at 5-6 Hz - which is too low for stereo odometry to work. Will need to fix that before going out to the park again. I think it was because the uncompressed ROS topics cannot be written to disk at 15fps. (just a guess. Perhaps that's wrong and the ROS bag is actually at 15fps and something else is to blame). My guess is that we might need to rosrecord compressed the ROS topics. (This is why we compress the LCM data immediately)

**Comment by gtinchev** [comment]
Rotation speed now correctly estimated. Video: https://www.dropbox.com/s/hfonr6ulzpskju9/loam_lidar_sweep_fixed.ogv?dl=0

**Comment by mauricefallon** [comment]
happy to merge this in if you wish

**Comment by gtinchev** [comment]
I have created a branch on ipab-slmc/loam_continuous. So the pull request is no longer needed.

**Pull request closed without merging**
